version: "3"
services:
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile  # Path to your Dockerfile for NestJS app
    ports:
      - "80:80"
    # environment:
    #   - NODE_ENV=production
    logging:
      driver: "datadog"
      options:
        "no-verify": "true"
        "tag": "nestjs-app"

  datadog:
    image: datadog/agent:latest
    environment:
      - DD_API_KEY=30bf3deaa143cfc4f3d5d3198f12e98e
      - DD_SITE=us5.datadoghq.com
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/proc/:/host/proc/:ro'
      - '/sys/fs/cgroup/:/host/sys/fs/cgroup:ro'
    ports:
      - "8125:8125/udp"
      - "8126:8126"
